authentication/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static
from django.views import defaults as default_views
from authentication.api import LoginView, LogoutView
from invoices.views import home
from authentication.views import (
    update_vertrieblers,
    delete_unused_data,
    update_elektrikers,
    protected_schema_view,
    zoho_callback,
)

app_name = "authentication"

# General URL patterns for authentication and home page
general_patterns = [
    path("", home, name="home"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("auth/callback", zoho_callback, name="zoho_callback"),
]

# URL patterns related to updating various entities
update_patterns = [
    path("update_vertrieblers/", update_vertrieblers, name="update_vertrieblers"),
    path("delete_unused_data/", delete_unused_data, name="delete_unused_data"),
    path("admin/update_elektrikers/", update_elektrikers, name="update_elektrikers"),
    path("admin/schema/", protected_schema_view, name="schema_view"),
]

# URL patterns handling various HTTP error statuses
error_handling_patterns = [
    re_path(
        r"^400/$",
        default_views.bad_request,
        kwargs={"exception": Exception("Bad Request!")},
    ),
    re_path(
        r"^403/$",
        default_views.permission_denied,
        kwargs={"exception": Exception("Permission Denied")},
    ),
    re_path(
        r"^404/$",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    re_path(r"^500/$", default_views.server_error),
]

# Concatenation of all the URL pattern groups along with static file URL patterns
urlpatterns = (
    general_patterns
    + update_patterns
    + error_handling_patterns
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.views import defaults as default_views
from invoices.views import handler403, handler404, handler500
from authentication.views import (
    update_vertrieblers,
    update_elektrikers,
    delete_unused_data,
    protected_schema_view,
)


def include_with_namespace(pattern_prefix, app_name):
    """Include patterns with namespace.

    Args:
        pattern_prefix (str): The prefix for the pattern.
        app_name (str): The application name.

    Returns:
        object: An include() object with specified namespace.
    """
    return include((pattern_prefix, app_name), namespace=app_name)


# Admin and Special Pages Paths
urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path(
        "adminfeautures/",
        include_with_namespace("adminfeautures.urls", "adminfeautures"),
    ),
    path("update_vertrieblers/", update_vertrieblers, name="update_vertrieblers"),
    path("update_elektrikers/", update_elektrikers, name="update_elektrikers"),
    path("delete_unused_data/", delete_unused_data, name="delete_unused_data"),
    path("admin/schema/", protected_schema_view, name="schema_view"),
]

# General Paths
urlpatterns += [
    path("", include("authentication.urls", namespace="authentication")),
    path("", include("vertrieb_interface.urls", namespace="vertrieb_interface")),
    # path("", include('authentication.api_urls')),
    # path("", include('vertrieb_interface.api.vertrieb_angebot_api_urls')),
    path(
        "proj/", include("projektant_interface.urls", namespace="projektant_interface")
    ),
    path("elektriker_interface/", include("invoices.urls", namespace="invoices")),
    path(
        "elektriker_kalender/",
        include("elektriker_kalender.urls", namespace="elektriker_kalender"),
    ),
    # path("__debug__/", include("debug_toolbar.urls")),
]

# Error Handling Paths
error_handling_patterns = [
    re_path(
        r"^400/$",
        default_views.bad_request,
        kwargs={"exception": Exception("Bad Request!")},
    ),
    re_path(
        r"^403/$",
        default_views.permission_denied,
        kwargs={"exception": Exception("Permission Denied")},
    ),
    re_path(
        r"^404/$",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    re_path(r"^500/$", default_views.server_error),
]

# Adding additional error handling paths in DEBUG mode
if settings.DEBUG:
    error_handling_patterns += [
        re_path(r"^403/$", handler403),
        re_path(r"^404/$", handler404),
        re_path(r"^500/$", handler500),
    ]

urlpatterns += error_handling_patterns

# Static and Media Paths
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elektriker_kalender/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from elektriker_kalender import views

app_name = "elektriker_kalender"

urlpatterns = [
    path(
        "elektriker_kalender/", views.CalendarView.as_view(), name="elektriker_kalender"
    ),
    path(
        "elektriker_kalender/get_elektriker_kalender/",
        views.ElektrikerKalenderView.as_view(),
        name="get_elektriker_kalender",
    ),
    path(
        "elektriker_kalender/elektriker_kalender_list/",
        views.ViewCalendarList.as_view(),
        name="elektriker_kalender_list",
    ),
    path(
        "position/delete/<int:id>/",
        views.PositionDeleteView.as_view(),
        name="position_delete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoices/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from invoices import views


app_name = "invoices"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("profile/", views.profile, name="profile"),
    path("view_orders/", views.ViewOrders.as_view(), name="view_orders"),
    path("help/", views.help, name="help"),
    path("create_invoice/", views.create_invoice, name="create_invoice"),
    path("api/sync_data", views.sync_data, name="sync_data"),
    path(
        "edit_invoice/<str:invoice_id>/",
        views.EditInvoiceView.as_view(),
        name="edit_invoice",
    ),
    path("create_pdf/<invoice_id>", views.create_pdf, name="create_pdf"),
    path("create_xlsx/<invoice_id>'/", views.create_excel, name="create_excel"),
    path("process_files/", views.ProcessFilesView.as_view(), name="process_files"),
    path("tom/", views.tom, name="tom"),
    path(
        "pdf_invoices_list/",
        views.PDFInvoicesListViewCBV.as_view(),
        name="pdf_invoices_list",
    ),
    path(
        "xlsx_invoices_list/",
        views.EXCELInvoicesListViewCBV.as_view(),
        name="excel_invoices_list",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elektriker_kalender/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from authentication.models import User
from django.views.generic import DetailView, ListView
from django.views import View
from django.http import JsonResponse
from django.shortcuts import redirect, render
from elektriker_kalender.forms import PositionForm
from elektriker_kalender.models import ElectricCalendar, Position
from django.shortcuts import get_object_or_404
from authentication.models import User
from authentication.fetch_elektrikers import (
    fetch_all_elektrik_angebots,
    extract_ids,
    fetch_all_detailed_elektrik_records,
)
from dotenv import load_dotenv
from elektriker_kalender.utils import create_instances
from config.settings import ENV_FILE

load_dotenv(ENV_FILE)


def filter_data_by_elektriker_id(json_data, elektriker_id):
    filtered_data = []
    for item in json_data:
        elektriker = item["data"]["Elektriker"]
        if elektriker["ID"] == elektriker_id:
            filtered_data.append(item)
    return filtered_data


class ElektrikerKalenderView(LoginRequiredMixin, View):
    def get_elektriker_kalender(self, request):
        print("Starting elektriker kalender update...")
        elektriker = get_object_or_404(User, zoho_id=request.user.zoho_id)
        data = fetch_all_elektrik_angebots()
        ids = extract_ids(data)
        fetched_records = fetch_all_detailed_elektrik_records(ids)
        print(elektriker.zoho_id)
        elektriker_id = str(elektriker.zoho_id)
        filtered_data_by_id = filter_data_by_elektriker_id(
            fetched_records, elektriker_id
        )
        elektriker.zoho_data_text = filtered_data_by_id
        elektriker.save()
        return filtered_data_by_id

    def get(self, request, *args, **kwargs):
        kalender_user_data = self.get_elektriker_kalender(request)
        user = request.user
        kurz = user.kuerzel
        create_instances(kalender_user_data, kurz)
        return render(request, "invoices/elektriker_kalender.html")
        # return JsonResponse(
        #     {"status": "success", "elektriker_kaleder": kalender_user_data}
        # )


def elektriker_check(user):
    return User.objects.filter(id=user.id, beruf="Elektriker").exists()


def verkaufer_check(user):
    return User.objects.filter(id=user.id, beruf="Vertrieb").exists()


class ElektrikerCheckMixin(UserPassesTestMixin):
    def test_func(self):
        return elektriker_check(self.request.user)  # type: ignore


class CalendarView(LoginRequiredMixin, DetailView):
    model = ElectricCalendar
    template_name = "invoices/elektriker_kalender.html"
    context_object_name = "elektriker_kalender"

    def get_object(self, queryset=None):
        return get_object_or_404(ElectricCalendar, user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["elektriker_kalender"] = ElectricCalendar.objects.get(
            user=self.request.user
        )
        # context["kundendata_objects"] = KundenData.objects.filter(calendar=self.object)
        context["position_form"] = PositionForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        kundendata_id = request.POST.get("kundendata")
        # kundendata = get_object_or_404(KundenData, id=kundendata_id)
        position_form = PositionForm(request.POST)

        if position_form.is_valid():
            position = position_form.save(commit=False)
            # position.kunde = kundendata
            position.save()
            return redirect("calendar")

        return self.render_to_response(
            self.get_context_data(
                position_form=position_form,
            )
        )


class ViewCalendarList(ElektrikerCheckMixin, ListView):
    model = ElectricCalendar
    template_name = "invoices/elektriker_kalender_list.html"
    context_object_name = "elektriker_kalenders"


class PositionDeleteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        position = get_object_or_404(Position, id=kwargs.get("id"))
        position.delete()
        return redirect("calendar")

templates/invoices/create_invoice.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="container">
        <h2>Kunden Data</h2>
        {{ form_kunden_data.as_p }}
    </div>
    <div class="container">
        <h2>Add Positions</h2>
        {{ form_position.as_p }}
    </div>
    <input type="submit" value="Save Invoice">
</form>
{% endblock %}

templates/invoices/elektriker_kalender_list.html
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<!-- JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css"/>

<!-- DataTables JS -->
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>   
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;700&display=swap" rel="stylesheet">    
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/view_orders.css' %}">
<style>
    body {
        background-image: url("{% static 'img/juno-background-dark.png' %}");
        color: #FFF; 
    }

    /* Your CSS styles here */
</style>
<div class="container mt-4 text-white"> 
    <a href="{% url 'invoices:home' %}" class="btn btn-primary" style="width: 120px;">Zurück</a>
    <div class="search-bar-container">
        <form method="get" action="" class="form-inline my-2 my-lg-0"> 
            <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search..." aria-label="Search" value="{{ request.GET.q }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
       
    <div class="table-container">
        <table class="table table-striped" id="calendarTable">
        <thead>
            <tr>
                <th scope="col">Kalender ID</th>
                <th scope="col">Datum</th>
                <th scope="col">Elektriker</th>
                <!-- Add more headers if necessary -->
            </tr>
        </thead>
        <tbody>
            {% for kalender in elektriker_kalenders %}
                <tr>
                    <td>{{ kalender.calendar_id }}</td>
                    <td>{{ kalender.current_date }}</td>
                    <td>{{ kalender.user.email }}</td>
                    <!-- Add more data cells if necessary -->
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">No calendar entries found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

</div>
{% endblock %}

{% block scripts %}
<script>
$(document).ready(function() {
    $('#calendarTable').DataTable();
} );
</script>
{% endblock %}

templates/invoices/help.html
{% extends 'invoices/base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="de">

{% block head %}
   
        <meta charset="utf-8" />
        <title>Help | Juno-Solar Administration Tool</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Coderthemes" name="Sam Ivanov" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">

        <!-- Theme Config Js -->
        <script src="{% static 'assets/js/hyper-config.js' %}"></script>

        <!-- App css -->
        <link href="{% static 'assets/css/app-saas.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

        <!-- Icons css -->
        <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />  

{% endblock %}
            <!-- ============================================================== -->
            <!-- Start Page Content here -->
            <!-- ============================================================== -->
{% block content %}
{% if form.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li><strong>{{ field.label }}:</strong> {{ error|escape }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

<body>
    <div class="content-page">
        <div class="content">
            <div class="container-fluid">
                <p></p>
                <div class="row">
                    <div class="col-xl-8">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="header-title mb-3">Chat-Assistant</h4>
                                <div class="chat-conversation">
                                    <div data-simplebar style="height:400px">
                                        <ul class="conversation-list">
                                            <!-- The chat messages will be inserted here by JavaScript -->
                                        </ul>
                                    </div>
                                    <form class="needs-validation" name="chat-form" id="chat-form" novalidate>
                                        <div class="row">
                                            <div class="col">
                                                <input type="text" class="form-control chat-input" placeholder="Geben Sie hier den Text ein" required>
                                                <div class="valid-tooltip">
                                                    Gut, genau...
                                                </div> 
                                            </div>
                                            <div class="col-auto d-grid">
                                                <button type="submit" class="btn btn-soft-success chat-send waves-effect waves-light">Send</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- container -->
        </div> <!-- content -->
    </div>

{% endblock %}
  
{% block extra_js %}
        <!-- Vendor js -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{% static 'assets/js/vendor.min.js' %}"></script>

        <!-- Chart.js -->
        <script src="{% static 'assets/vendor/chart.js/chart.min.js' %}"></script>

        <!-- Profile Demo App js -->
        <script src="{% static 'assets/js/pages/demo.profile.js' %}"></script>
        <script src="{% static 'assets/js/ui/component.chat.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'assets/js/app.min.js' %}"></script>
{% endblock %}
    </body>
</html>

templates/invoices/view_orders.html
{% extends 'invoices/base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="de">

{% block head %}
   
        <meta charset="utf-8" />
        <title>Alle Angebote | Juno-Solar Administration Tool</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
        <meta content="Coderthemes" name="Sam Ivanov" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">

        <!-- Theme Config Js -->
        <script src="{% static 'assets/js/hyper-config.js' %}"></script>
        <!-- Datatables css -->
        <link href="{% static 'assets/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/vendor/datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/vendor/datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/vendor/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/vendor/datatables.net-select-bs5/css/select.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />

        <!-- App css -->
        <link href="{% static 'assets/css/app-saas.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

        <!-- Icons css -->
        <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />  

{% endblock %}
{% block content %}
            <!-- ============================================================== -->
            <!-- Start Page Content here -->
            <!-- ============================================================== -->

            <div class="content-page">
                <div class="content">
            
                    <!-- Start Content-->
                    <div class="container-fluid">
                        
                                    
                                   <!-- start page title -->
                        <p></p>
            
                        <div class="row">
                            <div class="col-12">
                                <div class="card d-block">
                                    <div class="card-body">
            
                                                    
                                                    <div class="table-container">
                                                        <table id="scroll-horizontal-datatable" class="table w-100 nowrap">
                                                <thead>
                                                    <tr>
                                                        <th>Angebot ID</th>
                                                        <th>Datum</th>
                                                        <th>Kunde</th>
                                                        <th>Bestandteile</th>
                                                        <th>Angebot PDF generieren</th>
                                                        <th>Angebot EXCEL generieren</th>
                                                        <th>Zugriff auf die Bearbeitung</th>
                                                        <th>Status</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for invoice in invoices %}
                                                        <tr>
                                                            <td>{{ invoice.invoice_id }}</td>
                                                            <td>{{ invoice.current_date }}</td>
                                                            <td>{{ invoice.kunden_data.kunden_name }}</td>
                                                            <td>
                                                                <a href="{% url 'invoices:edit_invoice' invoice.invoice_id %}" class="text-body fw-bold">Zeigen</a>
                                                            </td>
                                                            <td>
                                                                {% if invoice.is_locked %}
                                                                <a href="{% url 'invoices:create_pdf' invoice.invoice_id %}" class="text-body fw-bold">PDF erstellen</a>
                                                                {% endif %}
                                                            </td>
                                                            <td>
                                                                {% if invoice.is_locked %}
                                                                <a href="{% url 'invoices:create_excel' invoice.invoice_id %}" class="text-body fw-bold">EXCEL erstellen</a>
                                                                {% endif %}
                                                            </td>
                                                            <td>{{ invoice.is_locked|yesno:"Nicht verfügbar,Verfügbar" }}</td>
                                                            <td>{{ invoice.is_synced|yesno:"Synced,Not Synced" }}</td>
                                                        </tr>
                                                    {% empty %}
                                                        <tr>
                                                            <td colspan="8">No orders found.</td>
                                                        </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div> <!-- end card-body-->
                                </div> <!-- end card-->
                            </div> <!-- end col -->
                        </div>
 
                        
                        <!-- end row -->

                        

                        

                    </div>
                    <!-- container -->

                </div>
                <!-- content -->

                <!-- Footer Start -->
                
                <!-- end Footer -->
                
            </div>

            <!-- ============================================================== -->
            <!-- End Page content -->
            <!-- ============================================================== -->


        <!-- END wrapper -->

        <!-- Theme Settings -->
        
    {% endblock %}   
    {% block scripts %}
        <!-- Vendor js -->
        <script>
            // TopBar Light Dark
            var themeColorToggle = document.getElementById('light-dark-mode');

            // On page load, check local storage for saved theme and apply it.
            // If there is no saved theme, default to 'dark'
            var savedTheme = localStorage.getItem('theme') || 'dark';
            self.changeLayoutColor(savedTheme);
            self.config.theme = savedTheme;

            if (themeColorToggle) {
                themeColorToggle.addEventListener('click', function (e) {

                    if (self.config.theme === 'dark') {
                        self.changeLayoutColor('light');
                        self.config.theme = 'light';
                        localStorage.setItem('theme', 'light');
                    } else {
                        self.changeLayoutColor('dark');
                        self.config.theme = 'dark';
                        localStorage.setItem('theme', 'dark');
                    }
                });
            }

            var resetBtn = document.querySelector('#reset-layout')
            if (resetBtn) {
                resetBtn.addEventListener('click', function (e) {
                    self.resetTheme();
                });
            }  
        </script>
        <script>
            // Wait until the DOM is fully loaded
            document.addEventListener("DOMContentLoaded", function() {
                // Get the link element
                var link = document.getElementById("create-invoice-link");
        
                // Add a click event listener to the link
                link.addEventListener("click", function(event) {
                    // Prevent the link's default behavior
                    event.preventDefault();
        
                    // Submit the form
                    document.getElementById("create-invoice-form").submit();
                });
            });
        </script>
{% endblock %}
{% block extra_js %}
        <script src="{% static 'assets/js/vendor.min.js' %}"></script>
        
        <!-- Code Highlight js -->
        <script src="{% static 'assets/vendor/highlightjs/highlight.pack.min.js' %}"></script>
        <script src="{% static 'assets/vendor/clipboard/clipboard.min.js' %}"></script>
        <script src="{% static 'assets/js/hyper-syntax.js' %}"></script>
        
        <!-- Datatables js -->
        <script src="{% static 'assets/vendor/datatables.net/js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-bs5/js/dataTables.bootstrap5.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-fixedcolumns-bs5/js/fixedColumns.bootstrap5.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
        <script src="{% static 'assets/vendor/datatables.net-select/js/dataTables.select.min.js' %}"></script>
        <!-- Daterangepicker js -->
        <script src="{% static 'assets/vendor/daterangepicker/moment.min.js' %}"></script>
        <script src="{% static 'assets/vendor/daterangepicker/daterangepicker.js' %}"></script>
        
        <!-- Apex Charts js -->
        <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
        
        <!-- Vector Map js -->
        <script src="{% static 'assets/vendor/admin-resources/jquery.vectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
        <script src="{% static 'assets/vendor/admin-resources/jquery.vectormap/maps/jquery-jvectormap-world-mill-en.js' %}"></script>
        
        <!-- Dashboard App js -->
        
        <!-- App js -->
        <script src="{% static 'assets/js/app.min.js' %}"></script>
        <!-- Datatable Demo Aapp js -->
        <script src="{% static 'assets/js/pages/demo.datatable-init.js' %}"></script>
{% endblock %}