config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.views import defaults as default_views
from invoices.views import handler403, handler404, handler500
from authentication.views import (
    update_vertrieblers,
    update_elektrikers,
    delete_unused_data,
    protected_schema_view,
)


def include_with_namespace(pattern_prefix, app_name):
    """Include patterns with namespace.

    Args:
        pattern_prefix (str): The prefix for the pattern.
        app_name (str): The application name.

    Returns:
        object: An include() object with specified namespace.
    """
    return include((pattern_prefix, app_name), namespace=app_name)


# Admin and Special Pages Paths
urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path(
        "adminfeautures/",
        include_with_namespace("adminfeautures.urls", "adminfeautures"),
    ),
    path("update_vertrieblers/", update_vertrieblers, name="update_vertrieblers"),
    path("update_elektrikers/", update_elektrikers, name="update_elektrikers"),
    path("delete_unused_data/", delete_unused_data, name="delete_unused_data"),
    path("admin/schema/", protected_schema_view, name="schema_view"),
]

# General Paths
urlpatterns += [
    path("", include("authentication.urls", namespace="authentication")),
    path("", include("vertrieb_interface.urls", namespace="vertrieb_interface")),
    # path("", include('authentication.api_urls')),
    # path("", include('vertrieb_interface.api.vertrieb_angebot_api_urls')),
    path(
        "proj/", include("projektant_interface.urls", namespace="projektant_interface")
    ),
    path("elektriker_interface/", include("invoices.urls", namespace="invoices")),
    path(
        "elektriker_kalender/",
        include("elektriker_kalender.urls", namespace="elektriker_kalender"),
    ),
    # path("__debug__/", include("debug_toolbar.urls")),
]

# Error Handling Paths
error_handling_patterns = [
    re_path(
        r"^400/$",
        default_views.bad_request,
        kwargs={"exception": Exception("Bad Request!")},
    ),
    re_path(
        r"^403/$",
        default_views.permission_denied,
        kwargs={"exception": Exception("Permission Denied")},
    ),
    re_path(
        r"^404/$",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    re_path(r"^500/$", default_views.server_error),
]

# Adding additional error handling paths in DEBUG mode
if settings.DEBUG:
    error_handling_patterns += [
        re_path(r"^403/$", handler403),
        re_path(r"^404/$", handler404),
        re_path(r"^500/$", handler500),
    ]

urlpatterns += error_handling_patterns

# Static and Media Paths
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoices/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from invoices import views


app_name = "invoices"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("profile/", views.profile, name="profile"),
    path("view_orders/", views.ViewOrders.as_view(), name="view_orders"),
    path("help/", views.help, name="help"),
    path("create_invoice/", views.create_invoice, name="create_invoice"),
    path("api/sync_data", views.sync_data, name="sync_data"),
    path(
        "edit_invoice/<str:invoice_id>/",
        views.EditInvoiceView.as_view(),
        name="edit_invoice",
    ),
    path("create_pdf/<invoice_id>", views.create_pdf, name="create_pdf"),
    path("create_xlsx/<invoice_id>'/", views.create_excel, name="create_excel"),
    path("process_files/", views.ProcessFilesView.as_view(), name="process_files"),
    path("tom/", views.tom, name="tom"),
    path(
        "pdf_invoices_list/",
        views.PDFInvoicesListViewCBV.as_view(),
        name="pdf_invoices_list",
    ),
    path(
        "xlsx_invoices_list/",
        views.EXCELInvoicesListViewCBV.as_view(),
        name="excel_invoices_list",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projektant_interface/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from projektant_interface import views

app_name = "projektant_interface"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("profile/", views.profile, name="profile"),
    path("help/", views.help, name="help"),
    path("populate_projects/", views.populate_projects_view, name="populate_projects"),
    path("view_orders/", views.ViewOrders.as_view(), name="view_orders"),
    path(
        "create_bauplan_pdf/<int:project_id>/",
        views.create_project_bauplan_pdf,
        name="create_bauplan_pdf",
    ),
    path("document_view/<int:project_id>/", views.document_view, name="document_view"),
    path("send_invoice/", views.send_invoice, name="send_invoice"),
    path("serve_pdf/<int:project_id>/", views.serve_pdf, name="serve_pdf"),
    path(
        "project/<int:project_id>/upload_jpg/", views.upload_jpg, name="upload_jpg"
    ),  # New URL pattern for JPG upload
    path(
        "project/<int:project_id>/update/", views.update_project, name="update_project"
    ),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/projektant/home.html
{% extends 'projektant/base.html'%}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
                <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <p></p>
                        </div>
                    </div>
                </div>
            </div>
                <!-- end page title -->
            <div class="row">
                <div class="col-xl-6">
                    <div class="card border-info border">
                        <div class="card-body">
                            <h5 class="card-title">Hallo, {{ user.first_name }} </h5>
                            <h6 class="card-subtitle text-muted">in diesem Portal kannst Du ein Angebote für Photovoltaikanlagen erstellen.</h6>
                        
                        </div>
                            <img class="img-fluid" style="margin: auto;" src="{% static 'img/junosolar_logo4.png' %}" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text"></p>
                            <div style="display: flex; gap: 15px;">
                                <a href="javascript:void(0);" class="btn btn-outline-info rounded-pill" data-bs-toggle="modal" data-bs-target="#info-alert-modal">
                                    Aktuelle Projekte aus ZOHO laden
                                    <span class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true" style="display: none;"></span>
                                    <span class="loading-text" style="display: none;">Der Download ist in Arbeit...</span>
                                </a>
                                
                                <div id="success-alert-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog modal-sm">
                                        <div class="modal-content modal-filled bg-success">
                                            <div class="modal-body p-4">
                                                <div class="text-center">
                                                    <i class="ri-check-line h1"></i>
                                                    <h4 class="mt-2">Erfolgreich!</h4>
                                                    <p class="mt-3">Die Daten wurden erfolgreich hochgeladen!</p>
                                                    <button type="button" class="btn btn-light my-2" data-bs-dismiss="modal">Weiter...</button>
                                                </div>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div>
                                <div id="info-alert-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog modal-sm">
                                        <div class="modal-content">
                                            <div class="modal-body p-4">
                                                <div class="text-center">
                                                    <i class="ri-information-line h1 text-info"></i>
                                                    <h4 class="mt-2">Achtung! </h4>
                                                    <p class="mt-3">Das Herunterladen der Daten von ZOHO kann einige Zeit dauern. Klicken Sie auf die Schaltfläche "Weiter..." und warten Sie, bis die Seite fertig geladen ist.</p>
                                                    
                                                    <button type="button" id="continueButtonn" class="btn btn-info my-2" data-bs-dismiss="modal">Weiter...</button>
                                                    
                                                    <script>
                                                        $(document).ready(function() {
                                                            function ajaxUpdateForAngebots($button, url) {
                                                                $button.find('.spinner-border').show();
                                                                $button.find('.loading-text').show();
                                                                
                                                                $.ajax({
                                                                    method: 'POST',
                                                                    url: url,
                                                                    data: { csrfmiddlewaretoken: '{{ csrf_token }}' },
                                                                    success: function() {
                                                                        $button.find('.spinner-border').hide();
                                                                        $button.find('.loading-text').hide();
                                                                        $('#success-alert-modal').modal('show');
                                                                    },
                                                                    error: function() {
                                                                        $button.find('.spinner-border').hide();
                                                                        $button.find('.loading-text').hide();
                                                                        alert('An error occurred while updating.');
                                                                    }
                                                                });
                                                            }

                                                            $('#continueButtonn').click(function() {
                                                                let $btn = $('[data-bs-target="#info-alert-modal"]');
                                                                ajaxUpdateForAngebots($btn, "{% url 'projektant_interface:populate_projects' %}");
                                                            });

                                                            $('#success-alert-modal').on('hidden.bs.modal', function (e) {
                                                                window.location.href = "{% url 'projektant_interface:home' %}";
                                                            });
                                                        });
                                                    </script>
                                                </div>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div>
                                
                            </div>
                            <p></p>                     
                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div>
                    

                <div class="col-xl-3 col-lg-12">
                    <div class="card border-info border">
                        <div class="card-body">
                            <span class="float-start m-2 me-4">
                                {% if user.avatar %}
                                <img src="{{ user.avatar.url }}" style="height: 100px;" alt="avatar-2" class="rounded-circle img-thumbnail">
                                {% endif %}
                            </span>
                            <div class="">
                                <h4 class="mt-1 mb-1">{{ user.first_name}} {{ user.last_name}}</h4>
                                <p class="font-13"> {{ user.email }} </p>
                                <ul class="mb-0 list-inline">
                                    <li class="list-inline-item me-3">
                                        <h5 class="mb-1">{{ user.kuerzel }}</h5>
                                        <p class="mb-0 font-13">{{ user.beruf }}</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
            
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <script>document.write(new Date().getFullYear())</script> © Juno-Solar Home 
                        </div>
                        <div class="col-md-6">
                            <div class="text-md-end footer-links d-none d-md-block">
                                <a href="javascript: void(0);">Info</a>
                                <a href="javascript: void(0);">Support</a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
    </div>
</div>
{% endblock%}

{% block javascript %}

{% endblock %}

{% block extra_js %}   
<!-- Daterangepicker js -->
<script src="{% static 'assets/js/vendor.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<!-- Code Highlight js -->
<script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'assets/js/app.min.js' %}"></script>
<script src="{% static 'assets/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'assets/vendor/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'assets/js/pages/demo.dashboard.js' %}"></script>
{% endblock %}  

templates/projektant/view_orders.html
{% extends 'projektant/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right"></div>
                            <h4 class="page-title">Liste der Projekte</h4>
                        </div>
                    </div>
                </div>           
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card d-block">
                        <div class="card-body">
                            <div class="table-container">
                                <table id="scroll-horizontal-datatable" class="table nowrap row-border order-column w-100">
                                    <thead>
                                        <tr>
                                            <th>Action</th>
                                            <th>Kunde Kundennummer</th>
                                            <th>Kunden Name</th>
                                            <th>Kunde Adresse PVA</th>
                                            <th>ID</th>
                                            <th>Kunde Email</th>
                                            <th>Status</th>
                                            <th>Auftrag Erteilt am</th>
                                            <th>Auftragsbestätigung</th>
                                            <th>Solar Module</th>
                                            <th>Modul Summe kWp</th>
                                            
                                            
                                            
                                            <th>Notstromversorgung Backup Box vorhanden</th>
                                            
                                            <th>Optimizer</th>
                                            <th>Speicher</th>
                                            
                                            
                                            
                                            
                                            
                                            <th>Wallbox</th>
                                            <th>Hub</th>
                                            
                                            <th>UK auf Lager</th>
                                            <th>Wechselrichter</th>
                                            <th>UK bestellt am</th>
                                            <th>Power Boost vorhanden</th>
                                            <th>Unterkonstruktion</th>
                                            
                                            <th>Status Einspeiseanfrage</th>
                                            
                                            <th>Nummer der PVA</th>
                                            
                                            <th>Kunde Telefon Festnetz</th>
                                            
                                            <th>Status Fertigmeldung</th>
                                            <th>Kunde Telefon mobil</th> 
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for project in projects %}
                                        <tr>
                                            <td><a href="{% url 'projektant_interface:create_bauplan_pdf' project.ID %}" class="btn btn-outline-info btn-sm">Bauplan erstellen</a></td>
                                            <td>{{ project.Kunde_Kundennummer }}</td>
                                            <td>{{ project.kunden_name }}</td>
                                            <td>{{ project.Kunde_Adresse_PVA }}</td>
                                            <td>{{ project.ID }}</td>
                                            <td>{{ project.Kunde_Email }}</td>
                                            <td>{{ project.Status }}</td>
                                            <td>{{ project.Auftrag_Erteilt_am }}</td>
                                            {% if project.Auftragsbest_tigung_versendet %}
                                                <td><span class="badge bg-success rounded-pill">Ja</span></td>
                                            {% else %}
                                                <td><span class="badge bg-danger rounded-pill">Nein</span></td>
                                            {% endif %}
                                            
                                            <td>{{ project.solar_module }}</td>
                                            <td>{{ project.Modul_Summe_kWp }}</td>
                                            
                                            {% if project.Notstromversorgung_Backup_Box_vorhanden %}
                                            <td><span class="badge bg-success rounded-pill">Ja</span></td>
                                            {% else %}
                                            <td><span class="badge bg-danger rounded-pill">Nein</span></td>
                                            {% endif %}
                                            
                                            <td>{{ project.Optimizer1 }}</td>
                                            <td>{{ project.speicher }}</td>
                                            
                                            
                                            
                                            
                                            
                                            <td>{{ project.wallbox }}</td>
                                            {% if project.Hub1 %}
                                            <td><span class="badge bg-success rounded-pill">Ja</span></td>
                                            {% else %}
                                            <td><span class="badge bg-danger rounded-pill">Nein</span></td>
                                            {% endif %}
                                            
                                            {% if project.UK_auf_Lager %}
                                            <td><span class="badge bg-success rounded-pill">Ja</span></td>
                                            {% else %}
                                            <td><span class="badge bg-danger rounded-pill">Nein</span></td>
                                            {% endif %}
                                            <td>{{ project.wechselrichter }}</td>
                                            <td>{{ project.UK_bestellt_am }}</td>
                                            {% if project.Power_Boost_vorhanden %}
                                            <td><span class="badge bg-success rounded-pill">Ja</span></td>
                                            {% else %}
                                                <td><span class="badge bg-danger rounded-pill">Nein</span></td>
                                            {% endif %}
                                            <td>{{ project.unterkonstrution }}</td>

                                            <td>{{ project.Status_Einspeiseanfrage }}</td>
                                            
                                            <td>{{ project.Nummer_der_PVA }}</td>
                                            
                                            <td>{{ project.Kunde_Telefon_Festnetz }}</td>
                                            
                                            <td>{{ project.Status_Fertigmeldung }}</td>
                                            <td>{{ project.Kunde_Telefon_mobil }}</td> 
                                        </tr>
                                        {% empty %}
                                            <tr>
                                                <td colspan="9">No orders found.</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div> 
                    </div>
                </div>
            </div>
        </div>
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <script>document.write(new Date().getFullYear())</script> © Juno-Solar Home 
                    </div>
                    <div class="col-md-6">
                        <div class="text-md-end footer-links d-none d-md-block">
                            <a href="javascript: void(0);">Info</a>
                            <a href="javascript: void(0);">Support</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'assets/js/vendor.min.js' %}"></script>
<script src="{% static 'assets/vendor/highlightjs/highlight.pack.min.js' %}"></script>
<script src="{% static 'assets/vendor/clipboard/clipboard.min.js' %}"></script>
<script src="{% static 'assets/js/hyper-syntax.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-bs5/js/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-fixedcolumns-bs5/js/fixedColumns.bootstrap5.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% static 'assets/vendor/datatables.net-select/js/dataTables.select.min.js' %}"></script>
<script src="{% static 'assets/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'assets/vendor/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'assets/vendor/admin-resources/jquery.vectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'assets/vendor/admin-resources/jquery.vectormap/maps/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{% static 'assets/js/app.min.js' %}"></script>
<script src="{% static 'assets/js/pages/demo.datatable-init.js' %}"></script>
{% endblock %}