authentication/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static
from django.views import defaults as default_views
from authentication.api import LoginView, LogoutView
from invoices.views import home
from authentication.views import (
    update_vertrieblers,
    delete_unused_data,
    update_elektrikers,
    protected_schema_view,
    zoho_callback,
)

app_name = "authentication"

# General URL patterns for authentication and home page
general_patterns = [
    path("", home, name="home"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("auth/callback", zoho_callback, name="zoho_callback"),
]

# URL patterns related to updating various entities
update_patterns = [
    path("update_vertrieblers/", update_vertrieblers, name="update_vertrieblers"),
    path("delete_unused_data/", delete_unused_data, name="delete_unused_data"),
    path("admin/update_elektrikers/", update_elektrikers, name="update_elektrikers"),
    path("admin/schema/", protected_schema_view, name="schema_view"),
]

# URL patterns handling various HTTP error statuses
error_handling_patterns = [
    re_path(
        r"^400/$",
        default_views.bad_request,
        kwargs={"exception": Exception("Bad Request!")},
    ),
    re_path(
        r"^403/$",
        default_views.permission_denied,
        kwargs={"exception": Exception("Permission Denied")},
    ),
    re_path(
        r"^404/$",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    re_path(r"^500/$", default_views.server_error),
]

# Concatenation of all the URL pattern groups along with static file URL patterns
urlpatterns = (
    general_patterns
    + update_patterns
    + error_handling_patterns
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.views import defaults as default_views
from invoices.views import handler403, handler404, handler500
from authentication.views import (
    update_vertrieblers,
    update_elektrikers,
    delete_unused_data,
    protected_schema_view,
)


def include_with_namespace(pattern_prefix, app_name):
    """Include patterns with namespace.

    Args:
        pattern_prefix (str): The prefix for the pattern.
        app_name (str): The application name.

    Returns:
        object: An include() object with specified namespace.
    """
    return include((pattern_prefix, app_name), namespace=app_name)


# Admin and Special Pages Paths
urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path(
        "adminfeautures/",
        include_with_namespace("adminfeautures.urls", "adminfeautures"),
    ),
    path("update_vertrieblers/", update_vertrieblers, name="update_vertrieblers"),
    path("update_elektrikers/", update_elektrikers, name="update_elektrikers"),
    path("delete_unused_data/", delete_unused_data, name="delete_unused_data"),
    path("admin/schema/", protected_schema_view, name="schema_view"),
]

# General Paths
urlpatterns += [
    path("", include("authentication.urls", namespace="authentication")),
    path("", include("vertrieb_interface.urls", namespace="vertrieb_interface")),
    # path("", include('authentication.api_urls')),
    # path("", include('vertrieb_interface.api.vertrieb_angebot_api_urls')),
    path(
        "proj/", include("projektant_interface.urls", namespace="projektant_interface")
    ),
    path("elektriker_interface/", include("invoices.urls", namespace="invoices")),
    path(
        "elektriker_kalender/",
        include("elektriker_kalender.urls", namespace="elektriker_kalender"),
    ),
    # path("__debug__/", include("debug_toolbar.urls")),
]

# Error Handling Paths
error_handling_patterns = [
    re_path(
        r"^400/$",
        default_views.bad_request,
        kwargs={"exception": Exception("Bad Request!")},
    ),
    re_path(
        r"^403/$",
        default_views.permission_denied,
        kwargs={"exception": Exception("Permission Denied")},
    ),
    re_path(
        r"^404/$",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    re_path(r"^500/$", default_views.server_error),
]

# Adding additional error handling paths in DEBUG mode
if settings.DEBUG:
    error_handling_patterns += [
        re_path(r"^403/$", handler403),
        re_path(r"^404/$", handler404),
        re_path(r"^500/$", handler500),
    ]

urlpatterns += error_handling_patterns

# Static and Media Paths
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoices/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from invoices import views


app_name = "invoices"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("profile/", views.profile, name="profile"),
    path("view_orders/", views.ViewOrders.as_view(), name="view_orders"),
    path("help/", views.help, name="help"),
    path("create_invoice/", views.create_invoice, name="create_invoice"),
    path("api/sync_data", views.sync_data, name="sync_data"),
    path(
        "edit_invoice/<str:invoice_id>/",
        views.EditInvoiceView.as_view(),
        name="edit_invoice",
    ),
    path("create_pdf/<invoice_id>", views.create_pdf, name="create_pdf"),
    path("create_xlsx/<invoice_id>'/", views.create_excel, name="create_excel"),
    path("process_files/", views.ProcessFilesView.as_view(), name="process_files"),
    path("tom/", views.tom, name="tom"),
    path(
        "pdf_invoices_list/",
        views.PDFInvoicesListViewCBV.as_view(),
        name="pdf_invoices_list",
    ),
    path(
        "xlsx_invoices_list/",
        views.EXCELInvoicesListViewCBV.as_view(),
        name="excel_invoices_list",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/logout.html
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="de" data-theme="dark" data-menu-color="dark">

    <head>
        <meta charset="utf-8" />
        <title>Logout | Juno-Solar Administration Tool</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <meta content="Coderthemes" name="Sam Ivanov" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
        
        
        <!-- Theme Config Js -->
        <script src="{% static 'assets/js/hyper-config.js' %}"></script>

        <!-- App css -->
        <link href="{% static 'assets/css/app-saas.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

        <!-- Icons css -->
        <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    </head>
    <style>
        body {
            background-image: url("{% static 'img/juno-background-dark.png' %}");
            width: 100%; 
            background-size: cover;
            background-attachment: fixed;   
        }
    </style>

    <body class="authentication-bg">
                <!-- Pre-loader -->
                <div id="preloader">
                    <div id="status">
                        <div class="bouncing-loader"><div ></div><div ></div><div ></div></div>
                    </div>
                </div>

        <div class="position-absolute start-0 end-0 start-0 bottom-0 w-100 h-100">
            <svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' viewBox='0 0 800 800'>
                <g fill-opacity='0.22'>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.1);" cx='400' cy='400' r='600'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.2);" cx='400' cy='400' r='500'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.3);" cx='400' cy='400' r='300'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.4);" cx='400' cy='400' r='200'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.5);" cx='400' cy='400' r='100'/>
                </g>
            </svg>
        </div>

        <div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5 position-relative">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-4 col-lg-5">
                        <div class="card">

                            <!-- Logo -->
                            <div class="card-header py-4 text-center bg-black bg-gradient bg-opacity-75">
                                <a href="{% url 'authentication:home' %}">
                                    <span><img src="{% static 'assets/images/JUNO-Solar-login.png' %}" alt="logo" height="50"></span>
                                </a>
                            </div>

                            <div class="card-body p-4">
                                
                                <div class="text-center w-75 m-auto">
                                    <h4 class="text-dark-50 text-center mt-0 fw-bold">Auf Wiedersehen!</h4>
                                    <p class="text-muted mb-4">Sie sind nun erfolgreich abgemeldet.</p>
                                </div>

                                <div class="logout-icon m-auto">
                                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                    viewBox="0 0 161.2 161.2" enable-background="new 0 0 161.2 161.2" xml:space="preserve">
                                        <path class="path" fill="none" stroke="#0acf97" stroke-miterlimit="10" d="M425.9,52.1L425.9,52.1c-2.2-2.6-6-2.6-8.3-0.1l-42.7,46.2l-14.3-16.4
                                            c-2.3-2.7-6.2-2.7-8.6-0.1c-1.9,2.1-2,5.6-0.1,7.7l17.6,20.3c0.2,0.3,0.4,0.6,0.6,0.9c1.8,2,4.4,2.5,6.6,1.4c0.7-0.3,1.4-0.8,2-1.5
                                            c0.3-0.3,0.5-0.6,0.7-0.9l46.3-50.1C427.7,57.5,427.7,54.2,425.9,52.1z"/>
                                        <circle class="path" fill="none" stroke="#0acf97" stroke-width="4" stroke-miterlimit="10" cx="80.6" cy="80.6" r="62.1"/>
                                        <polyline class="path" fill="none" stroke="#0acf97" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" points="113,52.8
                                            74.1,108.4 48.2,86.4 "/>

                                        <circle class="spin" fill="none" stroke="#0acf97" stroke-width="4" stroke-miterlimit="10" stroke-dasharray="12.2175,12.2175" cx="80.6" cy="80.6" r="73.9"/>
                                    </svg>
                                </div> <!-- end logout-icon-->

                            </div> <!-- end card-body-->
                        </div> <!-- end card-->

                        <div class="row mt-3">
                            <div class="col-12 text-center">
                                <p class="text-muted">Zurück zu <a href="{% url 'authentication:home' %}" class="text-muted ms-1"><b>Einloggen</b></a></p>
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            <script>document.write(new Date().getFullYear())</script> © Juno-Solar Home Gmbh
        </footer>
        <!-- Vendor js -->
        <script src="{% static 'assets/js/vendor.min.js' %}"></script>
        
        <!-- App js -->
        <script src="{% static 'assets/js/app.min.js' %}"></script>

    </body>
</html>

templates/pages-login.html
    {% load static %}
    {% load i18n %}
    {% load widget_tweaks %}
    <!DOCTYPE html>
    <html lang="de" data-theme="dark" data-menu-color="dark">

        <head>
            <meta charset="utf-8" />
            <title>Log In | JunoSolarHome App</title>
            <meta name="viewport" content="width=device-width, initial-scale=0.5">
        
            <meta content="Coderthemes" name="Sam Ivanov" />

            <!-- App favicon -->
            
            <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
            
            <!-- Theme Config Js -->
            <script src="{% static 'assets/js/hyper-config.js' %}"></script>

            <!-- App css -->
            <link href="{% static 'assets/css/app-saas.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

            <!-- Icons css -->
            <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        </head>
        <style>
        body {
            background-image: url("{% static 'img/3d-blue.jpg' %}");
            overflow: hidden;
            background-size: cover;
            background-attachment: fixed;   
        }
    </style>

        <body class="authentication-bg position-relative">
                        <!-- Pre-loader -->
        <div id="preloader">
            <div id="status">
                <div class="bouncing-loader"><div ></div><div ></div><div ></div></div>
            </div>
        </div>
            <div class="position-absolute start-0 end-0 start-0 bottom-0 w-100 h-100">
                <svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' viewBox='0 0 800 800'>
                    <g fill-opacity='0.22'>
                        <circle style="fill: rgba(var(--ct-primary-rgb), 0.1);" cx='400' cy='400' r='600'/>
                        <circle style="fill: rgba(var(--ct-primary-rgb), 0.2);" cx='400' cy='400' r='500'/>
                        <circle style="fill: rgba(var(--ct-primary-rgb), 0.3);" cx='400' cy='400' r='300'/>
                        <circle style="fill: rgba(var(--ct-primary-rgb), 0.4);" cx='400' cy='400' r='200'/>
                        <circle style="fill: rgba(var(--ct-primary-rgb), 0.5);" cx='400' cy='400' r='100'/>
                    </g>
                </svg>
            </div>
            <div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5 position-relative">

                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-xxl-4 col-lg-5">
                            <div class="card">

                                <div class="card-body p-4 bg-opacity-75">
                                    <div class="text-center w-75 m-auto">
                                        <h4 class="text-dark-50 text-center pb-0 fw-bold">Anmelden</h4>
                                        <p class="text-muted mb-4"></p>
                                    </div>

                                    <form method="POST" action="{% url 'authentication:login' %}" id="login-form">
                                        {% csrf_token %}

                                        <div class="mb-3">
                                            <label for="email" class="form-label">E-Mail Adresse</label>
                                            <input class="form-control" type="email" id="email" name="email" required="" placeholder="email">

                                        </div>

                                        <div class="mb-3">
                                            
                                            <label for="password" class="form-label">Passwort</label>
                                            <div class="input-group input-group-merge">
                                                <input type="password" id="password" name="password" class="form-control" placeholder="passwort">
                                                <div class="input-group-text" data-password="false">
                                                    <span class="password-eye"></span>
                                                </div>
                                            </div>
                                        </div>

                                        {% comment %} <div class="mb-3 mb-3">
                                            <div class="form-check">
                                                <input type="checkbox" class="form-check-input" id="checkbox-signin" checked>
                                                <label class="form-check-label" for="checkbox-signin">Erinnere mich</label>
                                            </div>
                                        </div> {% endcomment %}

                                        <div class="mb-3 mb-0 text-center">
                                            <button class="btn btn-primary" type="submit" id="login-button">Einloggen</button>
                                        </div>

                                    </form>
                                </div> <!-- end card-body -->
                            </div>
                            <!-- end card -->

                            <div class="row mt-3">
                                
                            </div>
                            <!-- end row -->

                        </div> <!-- end col -->
                    </div>
                    <!-- end row -->
                </div>
                <!-- end container -->
            </div>
            <!-- end page -->
            <footer class="footer footer-alt">
                2023 - <script>document.write(new Date().getFullYear())</script> © Juno-Solar Home Gmbh
            </footer>
            <!-- Vendor js -->
            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    var loginForm = document.getElementById('login-form');
                    loginForm.addEventListener('submit', function() {
                        // Disable the button
                        document.getElementById('login-button').disabled = true;
                        // Optional: Add a class to change the appearance of the button
                        document.getElementById('login-button').classList.add('disabled');
                    });
                });
            </script>
            
        
            <script src="{% static 'assets/js/vendor.min.js' %}"></script>
            
            <!-- App js -->
            <script src="{% static 'assets/js/app.min.js' %}"></script>

        </body>
    </html>

templates/pages-login2.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-menu-color="dark">

    <head>
        <meta charset="utf-8" />
        <title>Log In | Hyper - Responsive Bootstrap 5 Admin Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">
        
        <!-- Theme Config Js -->
        <script src="{% static 'assets/js/hyper-config.js' %}"></script>

        <!-- App css -->
        <link href="{% static 'assets/css/app-saas.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

        <!-- Icons css -->
        <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    </head>
    
    <body class="authentication-bg">
        <div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-4 col-lg-5">
                        <div class="card">

                            <!-- Logo -->
                            <div class="card-header py-4 text-center bg-primary">
                                <a href="index.html">
                                    <span><img src="assets/images/logo.png" alt="logo" height="22"></span>
                                </a>
                            </div>

                            <div class="card-body p-4">
                                
                                <div class="text-center w-75 m-auto">
                                    <h4 class="text-dark-50 text-center pb-0 fw-bold">Sign In</h4>
                                    <p class="text-muted mb-4">Enter your email address and password to access admin panel.</p>
                                </div>


                                <form id="loginForm" method="POST" action="{% url 'authentication:login' %}"></form>
                                    {% csrf_token %}


                                    <div class="mb-3">
                                        <label for="emailaddress" class="form-label">Email address</label>
                                        <input class="form-control" type="email" id="emailaddress" required="" placeholder="Enter your email">
                                    </div>

                                    <div class="mb-3">
                                    
                                        <label for="password" class="form-label">Password</label>
                                        <div class="input-group input-group-merge">
                                            <input type="password" id="password" class="form-control" placeholder="Enter your password">
                                            <div class="input-group-text" data-password="false">
                                                <span class="password-eye"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="mb-3 mb-3">
                                        <div class="form-check">
                                            <input type="checkbox" class="form-check-input" id="checkbox-signin" checked>
                                            <label class="form-check-label" for="checkbox-signin">Remember me</label>
                                        </div>
                                    </div>

                                    <div class="mb-3 mb-0 text-center">
                                        <button class="btn btn-primary" type="submit"> Log In </button>
                                    </div>

                                </form>
                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->

                        <div class="row mt-3">
                            <div class="col-12 text-center">
                                
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            2023 - <script>document.write(new Date().getFullYear())</script> © Juno-Solar Home Gmbh
        </footer>
        <!-- Vendor js -->
        <script src="{% static 'assets/js/vendor.min.js' %}"></script>
        
        <!-- App js -->
        <script src="{% static 'assets/js/app.min.js' %}"></script>

        <!-- Login js -->
        {% comment %} <script>
            .catch(error => console.error('Error:', error));

            document.getElementById('loginForm').addEventListener('submit', function(event) {
                event.preventDefault();

                var email = document.getElementById('emailaddress').value;
                var password = document.getElementById('password').value;

                fetch('ckjgsu1v.ngrok.app/auth/login/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        username: email,
                        password: password
                    }),
                    
                })
                                
                .then(response => response.json())
                .then(data => {
                    if (data.detail === 'Login successful') {
                        window.location.href = 'index.html';
                    } else {
                        alert('Invalid credentials');
                    }
                
                });
            });
        </script> {% endcomment %}

    </body>
</html>

templates/pages-logout.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>Logout | Hyper - Responsive Bootstrap 5 Admin Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico">
        
        <!-- Theme Config Js -->
        <script src="assets/js/hyper-config.js"></script>

        <!-- App css -->
        <link href="assets/css/app-saas.min.css" rel="stylesheet" type="text/css" id="app-style" />

        <!-- Icons css -->
        <link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    </head>

    <body class="authentication-bg">

        <div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-4 col-lg-5">
                        <div class="card">

                            <!-- Logo -->
                            <div class="card-header py-4 text-center bg-primary">
                                <a href="index.html">
                                    <span><img src="assets/images/logo.png" alt="logo" height="22"></span>
                                </a>
                            </div>

                            <div class="card-body p-4">
                                
                                <div class="text-center w-75 m-auto">
                                    <h4 class="text-dark-50 text-center mt-0 fw-bold">See You Again !</h4>
                                    <p class="text-muted mb-4">You are now successfully sign out.</p>
                                </div>

                                <div class="logout-icon m-auto">
                                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                    viewBox="0 0 161.2 161.2" enable-background="new 0 0 161.2 161.2" xml:space="preserve">
                                        <path class="path" fill="none" stroke="#0acf97" stroke-miterlimit="10" d="M425.9,52.1L425.9,52.1c-2.2-2.6-6-2.6-8.3-0.1l-42.7,46.2l-14.3-16.4
                                            c-2.3-2.7-6.2-2.7-8.6-0.1c-1.9,2.1-2,5.6-0.1,7.7l17.6,20.3c0.2,0.3,0.4,0.6,0.6,0.9c1.8,2,4.4,2.5,6.6,1.4c0.7-0.3,1.4-0.8,2-1.5
                                            c0.3-0.3,0.5-0.6,0.7-0.9l46.3-50.1C427.7,57.5,427.7,54.2,425.9,52.1z"/>
                                        <circle class="path" fill="none" stroke="#0acf97" stroke-width="4" stroke-miterlimit="10" cx="80.6" cy="80.6" r="62.1"/>
                                        <polyline class="path" fill="none" stroke="#0acf97" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" points="113,52.8
                                            74.1,108.4 48.2,86.4 "/>

                                        <circle class="spin" fill="none" stroke="#0acf97" stroke-width="4" stroke-miterlimit="10" stroke-dasharray="12.2175,12.2175" cx="80.6" cy="80.6" r="73.9"/>
                                    </svg>
                                </div> <!-- end logout-icon-->

                            </div> <!-- end card-body-->
                        </div> <!-- end card-->

                        <div class="row mt-3">
                            <div class="col-12 text-center">
                                <p class="text-muted">Back to <a href="pages-login.html" class="text-muted ms-1"><b>Log In</b></a></p>
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            2018 - <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
        </footer>
        <!-- Vendor js -->
        <script src="assets/js/vendor.min.js"></script>
        
        <!-- App js -->
        <script src="assets/js/app.min.js"></script>

    </body>
</html>