adminfeautures/urls.py
"""URL Configuration for the `adminfeatures` Django app.

The `urlpatterns` list routes URLs to views. For more information, please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""

from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static
from django.views import defaults as default_views
from adminfeautures.views import (
    user_list_view,
    update_solar_module_preise_view,
    update_wallbox_preise_view,
    update_optional_accessories_preise_view,
    update_andere_konfiguration_werte_view,
    avatar_upload_form,
    delete_user,
    test_delete_selected,
    PasswordUpdateView,
    ViewAdminOrders,
    UpdateAdminAngebot,
    DeleteAngebot,
    UserUpdateView,
    TopVerkauferContainerUpdateView,
    DeleteSelectedAngebots,
)

app_name = "adminfeautures"

# User management paths
user_management_patterns = [
    path("user-list/", user_list_view, name="user_list"),
    path("user/<int:pk>/edit/", UserUpdateView.as_view(), name="user-edit"),
    path("user/<int:pk>/delete/", delete_user, name="delete_user"),
    path(
        "user/<int:pk>/change_password/",
        PasswordUpdateView.as_view(),
        name="change_password",
    ),
    path("user/<int:user_id>/upload-avatar/", avatar_upload_form, name="upload_avatar"),
    path("user/<int:pk>/user-update/", UserUpdateView.as_view(), name="user-update"),
]

# User order management paths
user_order_management_patterns = [
    path("user/<int:user_id>/orders/", ViewAdminOrders.as_view(), name="user-orders"),
    path(
        "user/<int:user_id>/orders/<str:angebot_id>/",
        UpdateAdminAngebot.as_view(),
        name="update_admin_angebot",
    ),
    path(
        "user/<int:user_id>/orders/delete/<str:angebot_id>/",
        DeleteAngebot.as_view(),
        name="delete_angebot",
    ),
    path(
        "user/<int:user_id>/orders/test-delete-selected/",
        test_delete_selected,
        name="test_delete_selected",
    ),
    path(
        "user/<int:user_id>/orders/delete-selected/",
        DeleteSelectedAngebots.as_view(),
        name="delete_selected_angebots",
    ),
]

# Price management paths
price_management_patterns = [
    path(
        "prices/update_solar_module_preise/<int:module_id>/",
        update_solar_module_preise_view,
        name="update_solar_module_preise",
    ),
    path(
        "prices/update_wallbox_preise/<int:wallbox_id>/",
        update_wallbox_preise_view,
        name="update_wallbox_preise",
    ),
    path(
        "prices/update_optional_accessories_preise/<int:accessories_id>/",
        update_optional_accessories_preise_view,
        name="update_optional_accessories_preise",
    ),
    path(
        "prices/update_andere_konfiguration_werte/<int:andere_konfiguration_id>/",
        update_andere_konfiguration_werte_view,
        name="update_andere_konfiguration_werte",
    ),
]

# Error handling paths
error_handling_patterns = [
    re_path(
        r"^400/$",
        default_views.bad_request,
        kwargs={"exception": Exception("Bad Request!")},
    ),
    re_path(
        r"^403/$",
        default_views.permission_denied,
        kwargs={"exception": Exception("Permission Denied")},
    ),
    re_path(
        r"^404/$",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    re_path(r"^500/$", default_views.server_error),
]

urlpatterns = (
    user_management_patterns
    + user_order_management_patterns
    + price_management_patterns
    + error_handling_patterns
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

authentication/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static
from django.views import defaults as default_views
from authentication.api import LoginView, LogoutView
from invoices.views import home
from authentication.views import (
    update_vertrieblers,
    delete_unused_data,
    update_elektrikers,
    protected_schema_view,
    zoho_callback,
)

app_name = "authentication"

# General URL patterns for authentication and home page
general_patterns = [
    path("", home, name="home"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("auth/callback", zoho_callback, name="zoho_callback"),
]

# URL patterns related to updating various entities
update_patterns = [
    path("update_vertrieblers/", update_vertrieblers, name="update_vertrieblers"),
    path("delete_unused_data/", delete_unused_data, name="delete_unused_data"),
    path("admin/update_elektrikers/", update_elektrikers, name="update_elektrikers"),
    path("admin/schema/", protected_schema_view, name="schema_view"),
]

# URL patterns handling various HTTP error statuses
error_handling_patterns = [
    re_path(
        r"^400/$",
        default_views.bad_request,
        kwargs={"exception": Exception("Bad Request!")},
    ),
    re_path(
        r"^403/$",
        default_views.permission_denied,
        kwargs={"exception": Exception("Permission Denied")},
    ),
    re_path(
        r"^404/$",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    re_path(r"^500/$", default_views.server_error),
]

# Concatenation of all the URL pattern groups along with static file URL patterns
urlpatterns = (
    general_patterns
    + update_patterns
    + error_handling_patterns
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.views import defaults as default_views
from invoices.views import handler403, handler404, handler500
from authentication.views import (
    update_vertrieblers,
    update_elektrikers,
    delete_unused_data,
    protected_schema_view,
)


def include_with_namespace(pattern_prefix, app_name):
    """Include patterns with namespace.

    Args:
        pattern_prefix (str): The prefix for the pattern.
        app_name (str): The application name.

    Returns:
        object: An include() object with specified namespace.
    """
    return include((pattern_prefix, app_name), namespace=app_name)


# Admin and Special Pages Paths
urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path(
        "adminfeautures/",
        include_with_namespace("adminfeautures.urls", "adminfeautures"),
    ),
    path("update_vertrieblers/", update_vertrieblers, name="update_vertrieblers"),
    path("update_elektrikers/", update_elektrikers, name="update_elektrikers"),
    path("delete_unused_data/", delete_unused_data, name="delete_unused_data"),
    path("admin/schema/", protected_schema_view, name="schema_view"),
]

# General Paths
urlpatterns += [
    path("", include("authentication.urls", namespace="authentication")),
    path("", include("vertrieb_interface.urls", namespace="vertrieb_interface")),
    # path("", include('authentication.api_urls')),
    # path("", include('vertrieb_interface.api.vertrieb_angebot_api_urls')),
    path(
        "proj/", include("projektant_interface.urls", namespace="projektant_interface")
    ),
    path("elektriker_interface/", include("invoices.urls", namespace="invoices")),
    path(
        "elektriker_kalender/",
        include("elektriker_kalender.urls", namespace="elektriker_kalender"),
    ),
    # path("__debug__/", include("debug_toolbar.urls")),
]

# Error Handling Paths
error_handling_patterns = [
    re_path(
        r"^400/$",
        default_views.bad_request,
        kwargs={"exception": Exception("Bad Request!")},
    ),
    re_path(
        r"^403/$",
        default_views.permission_denied,
        kwargs={"exception": Exception("Permission Denied")},
    ),
    re_path(
        r"^404/$",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    re_path(r"^500/$", default_views.server_error),
]

# Adding additional error handling paths in DEBUG mode
if settings.DEBUG:
    error_handling_patterns += [
        re_path(r"^403/$", handler403),
        re_path(r"^404/$", handler404),
        re_path(r"^500/$", handler500),
    ]

urlpatterns += error_handling_patterns

# Static and Media Paths
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elektriker_kalender/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from elektriker_kalender import views

app_name = "elektriker_kalender"

urlpatterns = [
    path(
        "elektriker_kalender/", views.CalendarView.as_view(), name="elektriker_kalender"
    ),
    path(
        "elektriker_kalender/get_elektriker_kalender/",
        views.ElektrikerKalenderView.as_view(),
        name="get_elektriker_kalender",
    ),
    path(
        "elektriker_kalender/elektriker_kalender_list/",
        views.ViewCalendarList.as_view(),
        name="elektriker_kalender_list",
    ),
    path(
        "position/delete/<int:id>/",
        views.PositionDeleteView.as_view(),
        name="position_delete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoices/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from invoices import views


app_name = "invoices"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("profile/", views.profile, name="profile"),
    path("view_orders/", views.ViewOrders.as_view(), name="view_orders"),
    path("help/", views.help, name="help"),
    path("create_invoice/", views.create_invoice, name="create_invoice"),
    path("api/sync_data", views.sync_data, name="sync_data"),
    path(
        "edit_invoice/<str:invoice_id>/",
        views.EditInvoiceView.as_view(),
        name="edit_invoice",
    ),
    path("create_pdf/<invoice_id>", views.create_pdf, name="create_pdf"),
    path("create_xlsx/<invoice_id>'/", views.create_excel, name="create_excel"),
    path("process_files/", views.ProcessFilesView.as_view(), name="process_files"),
    path("tom/", views.tom, name="tom"),
    path(
        "pdf_invoices_list/",
        views.PDFInvoicesListViewCBV.as_view(),
        name="pdf_invoices_list",
    ),
    path(
        "xlsx_invoices_list/",
        views.EXCELInvoicesListViewCBV.as_view(),
        name="excel_invoices_list",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vertrieb_interface/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from vertrieb_interface.api_views import views
from vertrieb_interface.api_views.angebot_main_view import AngebotEditView
from vertrieb_interface.api_views.ticket_main_view import TicketNewEditView
from vertrieb_interface.api_views.kalkulation_view import KalkulationEditView
from vertrieb_interface.api_views.auto_field_view import VertriebAutoFieldView
from vertrieb_interface.api_views.alle_angebote_view import ViewOrders
from vertrieb_interface.api_views.alle_tickets_view import ViewOrdersTicket
from vertrieb_interface.api_views.document_PDF_view import DocumentView
from vertrieb_interface.api_views.document_ticket_new_PDF_view import DocumentViewTicketNew
from vertrieb_interface.api_views.document_and_calculation_PDF_view import (
    DocumentAndCalcView,
)

from django.views import defaults as default_views
from adminfeautures.views import UpdateAdminAngebot

app_name = "vertrieb_interface"

# Vertrieb URLs
vertrieb_patterns = [
    path("vertrieb/home/", views.home, name="home"),
    path("vertrieb/user_redirect", views.user_redirect_view, name="user_redirect"),
    path(
        "vertrieb/home/reset_calculator/",
        views.reset_calculator,
        name="reset_calculator",
    ),
    path(
        "vertrieb/edit_angebot/map/<str:angebot_id>/", views.map_view, name="map_view"
    ),
path(
        "vertrieb/edit_ticket_new/map/<str:ticket_id>/", views.map_view, name="map_view"
    ),
    path(
        "vertrieb/vertrieb_autofield/",
        VertriebAutoFieldView.as_view(),
        name="vertrieb_autofield",
    ),
    path("vertrieb/create_angebot/", views.create_angebot, name="create_angebot"),
    path("vertrieb/create_ticket_new/", views.create_ticket_new, name="create_ticket_new"),
    path(
        "vertrieb/create_angebot_redirect/",
        views.create_angebot_redirect,
        name="create_angebot_redirect",
    ),
    path("vertrieb/help/", views.help, name="help"),
    path(
        "vertrieb/calc_graph_display/",
        views.calc_graph_display,
        name="calc_graph_display",
    ),
    path("vertrieb/get_data/", views.get_data, name="get_data"),
    path(
        "vertrieb/load_user_angebots/",
        views.load_user_angebots,
        name="load_user_angebots",
    ),
    path("vertrieb/profile/", views.profile, name="profile"),
    path("vertrieb/view_orders/", ViewOrders.as_view(), name="view_orders"),
    path(
        "vertrieb/view_orders/delete/<str:angebot_id>/",
        views.DeleteUserAngebot.as_view(),
        name="delete_user_angebot",
    ),
    path("vertrieb/view_orders_ticket/", ViewOrdersTicket.as_view(), name="view_orders_ticket"),
    path(
        "vertrieb/view_orders_ticket/delete/<str:ticket_id>/",
        views.DeleteUserTicket.as_view(),
        name="delete_user_ticket_new",
    ),
    path(
        "vertrieb/edit_angebot/<str:angebot_id>/",
        AngebotEditView.as_view(),
        name="edit_angebot",
    ),
path(
        "vertrieb/edit_ticket_new/<str:ticket_id>/",
        TicketNewEditView.as_view(),
        name="edit_ticket_new",
    ),
    path(
        "vertrieb/edit_calc/<str:angebot_id>/",
        KalkulationEditView.as_view(),
        name="edit_calc",
    ),
    path(
        "vertrieb/update_admin_angebot/<str:angebot_id>/",
        UpdateAdminAngebot.as_view(),
        name="update_admin_angebot",
    ),
    path(
        "vertrieb/create_angebot_pdf_user/<str:angebot_id>",
        views.create_angebot_pdf_user,
        name="create_angebot_pdf_user",
    ),
    path(
        "vertrieb/create_ticket_new_pdf_user/<str:ticket_id>",
        views.create_ticket_new_pdf_user,
        name="create_ticket_new_pdf_user",
    ),
    path(
        "vertrieb/create_calc_pdf/<str:angebot_id>",
        views.create_calc_pdf,
        name="create_calc_pdf",
    ),
    path(
        "vertrieb/create_angebot_and_calc_pdf/<str:angebot_id>",
        views.create_angebot_and_calc_pdf,
        name="create_angebot_and_calc_pdf",
    ),
    path(
        "update_vertrieb_angebot/<int:angebot_id>/",
        views.UpdateVertriebAngebotView.as_view(),
        name="update_vertrieb_angebot",
    ),
    path(
        "vertrieb/pdf_angebots_list_view/",
        views.PDFAngebotsListView.as_view(),
        name="pdf_angebots_list_view",
    ),
path(
        "vertrieb/pdf_tickets_list_view/",
        views.PDFTicketsListView.as_view(),
        name="pdf_tickets_list_view",
    ),
    path(
        "PDFCalculationsListView/<str:angebot_id>/",
        views.PDFCalculationsListView,
        name="PDFCalculationsListView",
    ),
    path(
        "PDFTicketListView/<str:angebot_id>/",
        views.pdfticket_list_view,
        name="PDFTicketListView",
    ),
    path("serve_pdf/<str:angebot_id>/", views.serve_pdf, name="serve_pdf"),
    path(
        "serve_calc_pdf/<str:angebot_id>/", views.serve_calc_pdf, name="serve_calc_pdf"
    ),
    path(
        "serve_ticket_new_pdf/<str:ticket_id>/",
        views.serve_ticket_new_pdf,
        name="serve_ticket_new_pdf",
    ),
    path("document/<str:angebot_id>/", DocumentView.as_view(), name="document_view"),
    path("documentTicketNew/<str:ticket_id>/", DocumentViewTicketNew.as_view(), name="document_view_ticket_new"),
    path(
        "document_calc/<str:angebot_id>/",
        views.document_calc_view,
        name="document_calc_view",
    ),
    path(
        "document_and_calc_view/<str:angebot_id>/",
        DocumentAndCalcView.as_view(),
        name="document_and_calc_view",
    ),
    path("serve_dokumentation/", views.serve_dokumentation, name="serve_dokumentation"),
    path("documentation_view/", views.documentation_view, name="documentation_view"),
    path("send_invoice/<str:angebot_id>/", views.send_invoice, name="send_invoice"),
    path(
        "vertrieb/send_support_message/",
        views.send_support_message,
        name="send_support_message",
    ),
    path(
        "send_calc_invoice/<str:angebot_id>/",
        views.send_calc_invoice,
        name="send_calc_invoice",
    ),
    path("vertrieb/intermediate/", views.intermediate_view, name="intermediate_view"),
]

error_patterns = [
    re_path(
        r"^400/$",
        default_views.bad_request,
        kwargs={"exception": Exception("Bad Request!")},
    ),
    re_path(
        r"^403/$",
        default_views.permission_denied,
        kwargs={"exception": Exception("Permission Denied")},
    ),
    re_path(
        r"^404/$",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    re_path(r"^500/$", default_views.server_error),
]

urlpatterns = vertrieb_patterns + error_patterns
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/vertrieb/create_angebot.html
{% extends 'vertrieb/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="container">
        <h2>Kunden Data</h2>
        {{ form_kunden_data.as_p }}
    </div>
    <div class="container">
        <h2>Add Positions</h2>
        {{ form_position.as_p }}
    </div>
    <input type="submit" value="Save Invoice">
</form>
{% endblock %}

templates/vertrieb/document_ticket_new_view.html
{% extends 'vertrieb/base.html'%}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
<div class="content-page">
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'success' %}
      <script>
        $(document).ready(function() {
          $('#success-alert-modal').modal('show');
        });
      </script>
    {% endif %}
  {% endfor %}
{% endif %}

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                
                            </ol>
                        </div>
                        <h4 class="page-title">{{ ticket_id }}</h4>
                    </div>
                </div>
            </div>
            <form id="updateForm" method="POST" action="{% url 'vertrieb_interface:document_view_ticket_new' ticket_id=ticket_id %}" enctype="multipart/form-data">
            <div class="row">
                <div class="col-9">
                    
                        {% csrf_token %}
                        <div class="card border-info border">
                            <div class="card-body">
                                <h4 class="header-title">E-mail</h4>
                                <p class="text-muted font-14">Hier kannst du eine E-Mail schicken. Das PDF-Dokument wird automatisch an die Mail angehangen. </br>Der Standard-Text kann oben rechts in <i>Mein Profil</i> angepasst werden.</p>
                                {{ form.salutation }}
                                <p></p>
                                {{ form.text_for_email }}
                                <p></p>
                                {{ form.smtp_body }}
                                <p></p>
                                <h4 class="header-title">Empfänger</h4>
                                {{ form.email }}
                                <p class="text-muted font-14">Eine Kopie wird auch an Ihre E-Mail Adresse geschickt.</p>
                                
                                <div class="d-print-none mt-4">
                                    <div class="text-end">
                                        <button type="submit" id="email_send" class="btn btn-info">Email schicken</button>
                                        <div id="success-alert-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                                            <div class="modal-dialog modal-sm">
                                                <div class="modal-content modal-filled bg-success">
                                                    <div class="modal-body p-4">
                                                        <div class="text-center">
                                                            <i class="ri-check-line h1"></i>
                                                            <h4 class="mt-2">Erfolgreich!</h4>
                                                            <p class="mt-3">Die Nachverkauf-PDF wurde erfolgreich versendet!</p>
                                                            <a href="javascript:void(0);" onclick="document.getElementById('create-ticket-new-form').submit();" class="btn btn-light my-2" data-bs-dismiss="modal">Weiter</a>
                                                        </div>
                                                    </div>
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
            </div>

            </form>
            <div class="row">
                <div class="col-12">
                    <div class="card border-info border">
                        <div class="card-body">
                            <iframe src="{{ pdf_url }}" width='100%' height="900px">Your browser does not support iframes.</iframe>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <script>document.write(new Date().getFullYear())</script> © Juno-Solar Home 
                    </div>
                    <div class="col-md-6">
                        <div class="text-md-end footer-links d-none d-md-block">
                            <a type="submit" href="javascript:void(0)" id="send_support_message">Support</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <div class="d-print-none mt-4">
            <div class="text-end">
                <div id="success-alert-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog modal-sm">
                        <div class="modal-content modal-filled bg-success">
                            <div class="modal-body p-4">
                                <div class="text-center">
                                    <i class="ri-check-line h1"></i>
                                    <h4 class="mt-2">Erfolgreich!</h4>
                                    <p class="mt-3">Email support message wurde erfolgreich versendet!</p>
                                    <a role="button" href="{% url 'vertrieb_interface:home' %}" class="btn btn-light my-2" data-bs-dismiss="modal">Weiter</a>

                                </div>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div>
            </div>
        </div>
    </div>
</div>



            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    var loginForm = document.getElementById('updateForm');
                    loginForm.addEventListener('submit', function() {
                        // Disable the button
                        document.getElementById('email_send').disabled = true;
                        // Optional: Add a class to change the appearance of the button
                        document.getElementById('email_send').classList.add('disabled');
                    });
                });
            </script>
            <script type="text/javascript">
function navigateToUrl(url) {
    window.location.href = url;
}
</script>


{% endblock %}


        
 
        
            <!-- ============================================================== -->
            <!-- End Page content -->
            <!-- ============================================================== -->
{% block extrajs %}
        <script src="{% static 'assets/js/vendor.min.js' %}"></script>
        <script src="{% static 'assets/js/app.min.js' %}"></script>
        <!-- Code Highlight js -->
        <script src="{% static 'assets/vendor/highlightjs/highlight.pack.min.js' %}"></script>
        <script src="{% static 'assets/vendor/clipboard/clipboard.min.js' %}"></script>
        <script src="{% static 'assets/js/hyper-syntax.js' %}"></script>
        <!-- Simplemde Editor js -->
        <script src="{% static 'assets/vendor/simplemde/simplemde.min.js' %}"></script>
        <script src="{% static 'assets/js/pages/demo.simplemde.js' %}"></script>
         <!-- Quill Editor js -->
        <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>

        <!-- Quill Demo js -->
        <script src="{% static 'assets/js/pages/demo.quilljs.js' %}"></script> 
        <!-- end row -->


{% endblock %}

templates/vertrieb/intermediate_template.html
{% extends 'vertrieb/base.html'%}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
<!-- Pre-loader -->
                            <div id="preloader">
                    <div id="status">
                        <div class="bouncing-loader"><div ></div><div ></div><div ></div></div>
                    </div>
                </div>

<div class="content-page">
    <div class="content">
        <div class="container-fluid">
                <!-- start page title -->
            <div class="row">
                <div hidden class="col-12">
                                <form id="create-angebot-form" method="POST" action="{% url 'vertrieb_interface:create_angebot' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="create_blank_angebot" value="1">
                                    <button type="submit" class="btn btn-outline-info rounded-pill">Neues Angebot erstellen</button>
                                </form>

                                </div>
                                </div>
                                </div>
                                </div>
                                </div>
    <script>
        window.onload = function() {
            document.getElementById('create-angebot-form').submit();
        };
    </script>
        <script src="{% static 'assets/js/hyper-syntax.js' %}"></script>
        <script src="{% static 'assets/js/vendor.min.js' %}"></script>
        <script src="{% static 'assets/js/app.min.js' %}"></script>
{% endblock %}

templates/vertrieb/update_wallbox_preise.html
{% extends 'vertrieb/base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
            
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                        </div>
                        <h4 class="page-title">Admin Sei Liste</h4>
                    </div>
                </div>
            </div>      
            <!-- end page title -->

        <div class="row">

            <div class="col-lg-3">
                <div class="card">
                    <div class="d-flex card-header justify-content-between align-items-center">
                        <h4 class="header-title">Preis ändern</h4>
                        
                    </div>

                        <div class="card-body pt-0">
                            <div class="table-responsive">
                                <table class="table table-centered table-nowrap table-hover mb-0">
                                    <form method="POST" id="main-form" action="{% url 'adminfeautures:update_wallbox_preise' wallbox_id=wallbox.id %}">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <button type="submit" form="main-form" href="{% url 'adminfeautures:user_list' %}" id="save-all-forms" class="btn btn-soft-success rounded-pill">Speichern</button>
                                    </form>
                                </table>
                            </div> <!-- end table-responsive-->
                        </div> <!-- end card-body-->

                </div> <!-- end card-->
            </div> <!-- end col-->
        </div>
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <script>document.write(new Date().getFullYear())</script> © Juno-Solar Home 
                            </div>
                            <div class="col-md-6">
                                <div class="text-md-end footer-links d-none d-md-block">
                                    <a href="javascript: void(0);">Info</a>
                                    <a href="javascript: void(0);">Support</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
    </div>
</div>

{% endblock %}